# Generated by Django 2.2 on 2019-06-07 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_budgetline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='budget',
            name='currency',
            field=models.CharField(default='CZK', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetline',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='budget.Category'),
        ),
    ]
