# Generated by Django 2.2 on 2019-06-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20190607_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetline',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
