# Generated by Django 2.2 on 2019-06-07 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20190607_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetline',
            name='category',
        ),
    ]
