# Generated by Django 2.2 on 2019-06-07 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_remove_budgetline_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetline',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='budget.Category'),
        ),
    ]
