# Generated by Django 2.2 on 2019-06-07 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='rel',
            field=models.CharField(choices=[('VIEWER', 'VIEWER'), ('ADMIN', 'ADMIN')], max_length=8),
        ),
    ]
