# Generated by Django 2.2 on 2019-06-15 22:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_budget_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetline',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
